name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Create binaries
        run: npm run bundle

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/bundle/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: dist/bundle

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/bundle/supercet-node22-macos-arm64
            dist/bundle/supercet-node22-macos-x64
          draft: false
          prerelease: false
