name: Update Formula

on:
  push:
    tags:
      - "v*"

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Wait for release
        run: |
          echo "Waiting for release to be created..."
          sleep 30

      - name: Update formula
        run: |
          ruby scripts/update-formula.rb

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/supercet.rb
          git commit -m "Update formula for ${{ github.ref_name }}"
          git push

  test-formula:
    runs-on: macos-latest
    needs: update-formula
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "$HOME/.homebrew/bin" >> $GITHUB_PATH

      - name: Test formula
        run: |
          brew install --build-from-source ./Formula/supercet.rb
          supercet --help
